# Generated by Django 3.2.6 on 2021-08-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=2000, unique=True, verbose_name='이메일 주소')),
                ('nickname', models.CharField(default=None, max_length=200, verbose_name='닉네임')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 유무')),
                ('last_login_at', models.DateTimeField(verbose_name='최종 로그인 시간')),
                ('created_at', models.DateTimeField(verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(verbose_name='수정 시간')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
